### ISSUE TITLE
Role of server-bundle.js

### ISSUE THREAD

**Issue by nitish24p** [Limenius/symfony-react-sandbox#12]
Hey, just had a doubt, what exactly is the role of the server bundle. Is it possible to do server side rendering without generating this bundle via webpack. Also is this a one time command which i can use for my app, create the bundle and then run things normally, or does this start a node server which acts as a proxy to the symfony app. Could u please explain a bit in detail.. 

Thanks

**Comment by nacmartin** [comment]
hi, @nitish24p server bundle is the code that will be used to do the server rendering. It will probably share almost all the code with your client bundle, but sometimes, specially when using routing in React, you will want a different entry point, like https://github.com/Limenius/symfony-react-sandbox/blob/master/client/Recipes/startup/RecipesAppServer.jsx
