### ISSUE TITLE
Enabling Redux Breaks Page Navigation

### ISSUE THREAD

**Issue by willcode4food** [Limenius/symfony-react-sandbox#14]
When I enabled redux, and then try and navigate to a different page, all I get is the word Loading... and no page content.  A refresh of the browser displays the appropriate content.  I looks like its not making a round trip to the server.

**Comment by willcode4food** [comment]
Update:  Looks to be something with the conditional statements to that determines whether to show the loading text or not. Checking the props for the boolean fetching (local state) and if a recipe is populated (redux state) could be causing issues.  May want to refactor this to control the loading from the redux state only.  Just my opinion.  

In any case, commenting out the loading display logic allows the pages to load and the navigation to work.  The UX is just not as nice.

**Comment by nacmartin** [comment]
Thanks for this report. Sorry for the delay, I wanted to fix this along with a refactor of the Redux part of the app, and also bump some versions (especially React Router). It should be better now!
