### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Something went wrong evaluating JS code: result: "Error: Could not find store registered with name 'recipesStore'. Registered store names include [ ]. Maybe you forgot to register the store?"") in recipe/recipe.html.twig at line 7.

### ISSUE THREAD

**Issue by lingorus** [Limenius/symfony-react-sandbox#15]
Hello
I'm trying to run redux version but it's not working. 
There is a error:
An exception has been thrown during the rendering of a template ("Something went wrong evaluating JS code:
result: "Error: Could not find store registered with name 'recipesStore'. Registered store names include [ ]. Maybe you forgot to register the store?"") in recipe/recipe.html.twig at line 7.

What did I forget?

**Comment by lingorus** [comment]
Passed rendering option
{{ react_component('RecipesApp', {"rendering": "client_side"}) }}

**Comment by nacmartin** [comment]
This should have been fixed with last changes, thanks for reporting.
