### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by nblaudez** [Limenius/symfony-react-sandbox#16]
Hi,

I installed your application.
I ran composer install and npm install but i have this error when i try to reach the home page :+1: 

An exception has been thrown during the rendering of a template ("Something went wrong evaluating JS code:
result: "Error: Cannot find module "./recipes-redux/store/recipesStore""").

Someone can help me ?

Best regards

Nicolas Blaudez

**Comment by nacmartin** [comment]
Thanks for reporting this. The problem was that we were requiring files with the wrong case (`recipesStore` instead of `RecipesStore`), which is something that some filesystems can work with, but in others it is an error. It should be fixed now.
