### ISSUE TITLE
Documentation: file names/paths changed?

### ISSUE THREAD

**Issue by andosteinmetz** [Limenius/symfony-react-sandbox#17]
Under "Globally Expose your React Components," should the  paths `client/js/serverRegistration.js` and `client/js/clientEntryPoint.js` be changed to `cleint/startup/serverRegistration.jsx` and `client/startup/clientRegistration.jsx`?

**Comment by nacmartin** [comment]
Ah, yes, you are right, I changed them during the weekend and forgot to update the docs accordingly. Thanks for noticing.
