### ISSUE TITLE
Update to react-on-rails 6.6 when ready

### ISSUE THREAD

**Issue by mablae** [Limenius/symfony-react-sandbox#25]
This will basically use `<script>` tags instead of hidden `<div>` to transfer state into views.

See this PR: https://github.com/shakacode/react_on_rails/pull/660

**Comment by nacmartin** [comment]
Very interesting, not only the actual code but also all the discussion, thanks! I am watching the thread now and will try to adapt to it asap.

**Comment by nacmartin** [comment]
Ok, this change has finally been merged! https://github.com/shakacode/react_on_rails/pull/775
