### ISSUE TITLE
Documentation example not working

### ISSUE THREAD

**Issue by MichaelHindley** [Limenius/symfony-react-sandbox#28]
Hello,

when following the documention in README.MD, when getting to the command `npm run webpack-serverside`, npm errors out with `Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.  - configuration.output.path: The provided value "./app/Resources/webpack/" is not an absolute path!
`

See screenshot below.

![screen shot 2017-03-24 at 15 30 08](https://cloud.githubusercontent.com/assets/1016639/24298614/d18e9ace-10a6-11e7-9e40-66b8a1a9bd9b.png)

**Comment by nacmartin** [comment]
Thanks for reporting this, @MichaelHindley!

Webpack config doesn't accept relative paths anymore. Fixed.

**Comment by sufius** [comment]
Hello,

I've tested the example and its working fantastic, but unfortunately not on my smartphone (Android 6).

See screenshot below.

![screenshot_2017-11-16-09-53-41-624_com android browser](https://user-images.githubusercontent.com/1421570/32883117-c30d4bc4-cab6-11e7-9bfb-9daad3405ff4.png)

**Comment by nacmartin** [comment]
This is an urelated issue, right? I mean, the original issue has nothing to do with this one. Or am I missing anything?

If this is the case, could you open a separate issue?
