### ISSUE TITLE
Remove the hardcoded base_url for webpack asset package

### ISSUE THREAD

**Issue by robertodormepoco** [Limenius/symfony-react-sandbox#29]
As stated in the doc in [AppKernel.php](https://github.com/Limenius/symfony-react-sandbox/blob/master/app/AppKernel.php#L56) there is a conditional/hardcoded value for the base_url as stated in the issue title, this is not ideal if we want to develop using virtualhosts like in a virtualized environment, it will be better to handle this during the bundle configuration and leave the user to set the base_url in the config.yml file

**Comment by nacmartin** [comment]
Thanks @robertodormepoco! I have included your suggestion.
