### ISSUE TITLE
[Question] Symfony version selection 

### ISSUE THREAD

**Issue by joshhornby** [Limenius/symfony-react-sandbox#3]
I am thinking of using this great resource as a boilerplate for a new project, one question: Is there any reason you require `"symfony/symfony": "3.1.*@dev"` and not a more stable version? 

Thanks again for this resource and the blog write up :+1:

**Comment by nacmartin** [comment]
Ah, that is right. I just started by cloning the master of symfony-standard-edition and that is why the requirement is so harsh, but I think it makes sense to lower the requirements to 3.0, so there are less surprises. I will do it this evening. Thanks!

**Comment by nacmartin** [comment]
Here you go: 6494161f78fad6e59a52203d53ec2c5e08745e02
