### ISSUE TITLE
Events Handling

### ISSUE THREAD

**Issue by SofiaGR** [Limenius/symfony-react-sandbox#30]
First of all, thanks for this bundle. 

I recently integrated it with a symfony project and managed to render a few areas of the app using react and the exact structure this example follows, but I ran into an issue that I assume is related to react rendering on server side (it's using the default: both).

Whenever I tried to add even an onClick listener, once the page is rendered nothing will happen.

So my question is, if I have both the RecipesAppServer and the RecipesAppClient pointing to the same react component, what am I missing for click events to work?

Would an example be possible? I'd highly appreciate it!

**Comment by SofiaGR** [comment]
Nevermind, I figured out by searching through this repository where I had to include the client-bundle.js file.

**Comment by nacmartin** [comment]
Oh, sorry for not answering before. I had this on my TODO-list but couldn't find the time :/.

Thanks for reporting this. Do you think that the documentation could be improved somehow so it can help other users in the same situation?

**Comment by SofiaGR** [comment]
This Twig function, provided by ReactBundle, will render the React component RecipesApp in server and client modes. <-- this part of the documentation makes it seem that's all you need, but in reality, if you don't include the client-bundle.js file (and in my case the app kernel webpack part), it would never render anything in the client side. 

I'd say perhaps mention that in line 54 in the https://github.com/Limenius/symfony-react-sandbox/blob/132d5c716b8de21e2bbbeb457ccc80ea177660ea/app/Resources/views/base.html.twig you're adding the client-bundle.js file to the project.

Of course, with the way that is written, I think it will need the webpack appkernel part you already mentioned in the documentation though.
