### ISSUE TITLE
eslint ^4.x isnt suported by babel-eslint

### ISSUE THREAD

**Issue by grimpows** [Limenius/symfony-react-sandbox#36]
you should downgrade eslint requirement from ^4.0.0 to "^3.19.0" since 4.x isnt suported by babel-eslint 
see https://github.com/babel/babel-eslint#supported-eslint-versions
using 4.x throw an error

**Comment by nacmartin** [comment]
Ok, thanks, locked to these versions.

**Comment by grimpows** [comment]
you're welcome, your react bundle is really awesome ^^ really helped me to create a symfony/react project, dont really understand how you was using react on rail on symfony but that's rock !

**Comment by grimpows** [comment]
if i also can do a sugestion, i saw you speak about how to remove harcoded routes from symfony to react, my project use only one routes for react who is 
''''
react_root:
    path:     /
    defaults: { _controller: SWReactBundle:React:index}

react_homepage:
    path:     /{slug}
    defaults: { _controller: SWReactBundle:React:index,  slug: default}
    requirements:
        slug: '.+'

''''

i send a serialised router like this in controller to twig and from twig to react with your react bundle 
 
router look like this 

'''' 

'router' => [
                                'routes' =>[
                                        [
                                        'name' => 'admin',
                                        'path' => '/:locale/admin',
                                        'exact' => false,
                                        'show' => false,
                                        'component' => 'AdminNavbar',
                                        'switchs' => [
                                            [
                                                'name' => 'adminRoot',
                                                'path' => '/:locale/admin',
                                                'exact' => true,
                                                'component' => 'AdminRoot',
                                                'switchs' => []
                                            ],
                                            [
                                                'name' => 'adminNotFoud',
                                                'path' => '*',
                                                'exact' => false,
                                                'component' => 'NotFound',
                                                'switchs' => []
                                            ]
                                        ],
                                        'links' => [
                                            [
                                                'type' => 'internal',
                                                'path' => '/:locale/',
                                                'name' => 'homepage',
                                                
                                            ]
                                        ]
..... some more routes like this ''''

and in react i do this code to dynamicaly create the app from this router stored with redux 

''''

import React from 'react'
import  App  from '../container/App'
import  * as AllComponent from '../container/index'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'
import {
      Route,
      Switch,
      withRouter
} from 'react-router-dom'

class Routes extends React.Component {
        
    constructor(props){
        super(props)
        
    }
    
    addRoute(r,i){
        const Component = AllComponent[r.component]
        if( typeof(Component) === 'undefined'){
            if(this.props.env.devMode === true){
                console.log("'" + r.component + '\' component not found ! from ' , r)   
            }
            return false
        }
        return(
            <Component exact={r.exact} key={i} path={r.path}  >
                <Switch> 
                    { r.switchs.map(this.addRoute.bind(this))}
                </Switch>
            </Component>
        )
    }
    
    
    render() {
        return (
            <div>
                <App>
                    <Switch>
                       {
                        this.props.router.routes.map(this.addRoute.bind(this))
                       }
                    </Switch>
                </App>
            </div>
        );
    }
}

Routes.propTypes = {
    match: PropTypes.object.isRequired,
    location: PropTypes.object.isRequired,
    history: PropTypes.object.isRequired,
}

const mapStateToProps = (state) => (
    {
       localeManager: state.localeManager,
       request: state.request,
       router: state.router,
       env: state.env
    }
)

export default withRouter(connect(mapStateToProps)(Routes))

''''

if that can help ^^

**Comment by nacmartin** [comment]
Thanks! I will have a look at this solution. We definitely need a solution to integrate Symfony routing in the client side.

**Comment by grimpows** [comment]
i can truly explain much more better how i do that, but in fact, i can add any route in a second with this solution, i'm going to make a true manager with symfony where i'll be able to call it to add new route from any bundle, the manager then will be call in the controller and send all route added from anywhere, of course components called for route should be all imported from the ```` import  * as AllComponent from '../container/index' ```` that let you add/remove some route at any time, actualy i'm working on the dynamic navigation created from this router, that work well for now :)

**Comment by grimpows** [comment]
also note that routes are imported in a router declaration like you do in the react sandbox 
here is the code with the routes imported 
```` 
import React from 'react'
import { Provider } from 'react-redux'
import Routes from './modules/Routes'
import {
      BrowserRouter,
      StaticRouter,
      Route,
      Switch,
} from 'react-router-dom'


export default  (initialProps, context) => {
    
    const store = ReactOnRails.getStore('GlobalStore')
    const { location, base, serverSide } = context
    let Router
    
    // We render a different router depending on whether we are rendering server side
    // or client side. 
    if (  serverSide) {
        Router = (props) => (
            <StaticRouter basename={base} location={location} context={{}} >
                {props.children}
            </StaticRouter>
        )
    } else {
        Router = (props) => (
            <BrowserRouter basename={base}>
                {props.children}
            </BrowserRouter>
        )
    }
     
    
    return (
        <Provider store={store}>
            <Router>
                <Routes/>   
            </Router>
        </Provider>
    )
}


````
