### ISSUE TITLE
Problem with static routing "Invariant Violation: Browser history needs a DOM"

### ISSUE THREAD

**Issue by tato11** [Limenius/symfony-react-sandbox#39]
I'm trying to make server rendering work on Symfony applying this example "https://github.com/Limenius/symfony-react-sandbox/blob/master/client/js/recipes/startup/RecipesApp.js" but is just not working on server rendering... I'm not sure it it something with my environment or it is an outdated example with old log, could you help me to make this work?

Here is the code I am using right now:

```
import React from 'react'
import ReactOnRails from 'react-on-rails'
import { Provider } from 'react-redux'
import { browserHistory } from 'react-router'
import { Route } from 'react-router-dom'
import BrowserRouter from 'react-router-dom/BrowserRouter';
import StaticRouter from 'react-router-dom/StaticRouter';
import { ConnectedRouter } from 'react-router-redux';
import Component from './Component'

import {createBrowserHistory, createMemoryHistory} from 'history';


const Root =  (initialProps, context) => {                
    let Router
    const { location, base, serverSide } = context
    // We render a different router depending on whether we are rendering server side
    // or client side.
    if (serverSide) {
        Router = (props) => (
            <StaticRouter basename={base} location={location} context={{}} >
                {props.children}
            </StaticRouter>
        )
    } else {
        Router = (props) => (
            <BrowserRouter basename={base} >
                {props.children}
            </BrowserRouter>
        )
    }
    //const history =  createHistory()
    //store for this component
    //todo fix react router
    const store = ReactOnRails.getStore('store')    
    //todo fix router
    return (<Provider store={store}>                 
                <Router>                   
                   <Route path={`/:mode1/:mode2`} exact render={(obj) => <div>{JSON.stringify(obj)}</div>} />                 
                </Router>
            </Provider>)
}

export default Root
```

I'm using Symfony 3.3 + PHP7 and the following react environment:
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-on-rails": "^8.0.3",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8"

Thanks!

**Comment by nacmartin** [comment]
I just cloned the sandbox, installed the dependencies, and worked.

From what you say, it looks like when you are rendering serverside, it is using `BrowserRouter`, that will fail. In your code I see that you are getting the variable `serverside` from context and conditionally using a router or other, and that should work, but it doesn't. I'd inspect the value of `serverside` to see what is going on.
