### ISSUE TITLE
Example not working on Android 6

### ISSUE THREAD

**Issue by sufius** [Limenius/symfony-react-sandbox#43]
Hello,

I've tested the example and its working fantastic, but unfortunately not on my smartphone (Android 6).

See screenshot below.

![screenshot_2017-11-16-09-53-41-624_com android browser](https://user-images.githubusercontent.com/1421570/32897905-0cfa04f4-cae7-11e7-9e24-986bc216be6f.png)

**Comment by nacmartin** [comment]
If you are seeing the project correctly in a browser, but not in an android device, the problem, from what I see (not loading js/css assets) is that android cannot reach the port of your localhost from where Webpack is serving the assets.

This has nothing to do with this particular sandbox, it is a detail of a particular development set up.
