### ISSUE TITLE
windows “EPERM: operation not permitted” on build directory

### ISSUE THREAD

**Issue by nusje2000** [Limenius/symfony-react-sandbox#47]
Hi there, I'am trying out this repo but after a few builds on windows the build directory becomes unreadable, has anyone encountered this issue before or does someone have a fix for this problem (restarting fixes the problem but is annoying to do). Question can also be found on https://stackoverflow.com/questions/47823569/symfony-encore-windows-eperm-operation-not-permitted

**Comment by nusje2000** [comment]
EDIT: I was using docker to run my project. when I halted docker, I was able to remove the build file.

**Comment by nacmartin** [comment]
🤔 HI, @nusje2000, is there something we could fix or add to the docs to prevent this? If I try to run this sandbox from docker, will I find the error right away or is it something specific from your environment?

**Comment by nusje2000** [comment]
Hi @nacmartin, I don't think it has something to do with my environment. I think is has something to do with docker om windows. When I run the exact same project on linux (Ubuntu / Debian) it works fine but on windows it seems to fail after a the third to fourth time compiling.
