### ISSUE TITLE
[Question] Running this on Docker + nginx

### ISSUE THREAD

**Issue by Destroy666x** [Limenius/symfony-react-sandbox#50]
Hello,

I'm a back-end developer inexperienced when it comes to webpack and React. I have set up a Docker compose file with 3 containers: db, nginx and app. In app I'm running supervisor which then runs `php-fpm`, `yarn run webpack-serverside` and `yarn run webpack-dev`. The nginx configuration is more or less standard Symfony 4 one from documentation.

What's working: Symfony + server-side rendering (apart from some array to string conversion notices, fixed with this https://github.com/Limenius/ReactRenderer/commit/d48630434c374031041a21a7875e899e19f5958d). What's not working: client-side rendering, I get connection refused errors for `public/build` stuff (I guess `proxy_pass` is needed?), which doesn't seem to be generated in the first place - there's only `manifest.json`.

What am I missing?

**Comment by omarsoufiane** [comment]
Did you manage to install v8js extension on docker PHP ? @Destroy666x

**Comment by nacmartin** [comment]
I am closing this because lack of activity. If someone is running a similar setup, please don't hesitate to respond.
