### ISSUE TITLE
Howto apply jss server side styles to the base index.html file

### ISSUE THREAD

**Issue by sufius** [Limenius/symfony-react-sandbox#57]
Could you please provide an example or explain how to apply the following guide to your example app?

[https://material-ui.com/guides/server-rendering/](https://material-ui.com/guides/server-rendering/)

In that guid

```
...
<style id="jss-server-side">${css}</style>
...
```

is added to server sides base html file (in order to avoid flickering) and by this:

```
  ...
  // Remove the server-side injected CSS.
  componentDidMount() {
    const jssStyles = document.getElementById('jss-server-side');
    if (jssStyles && jssStyles.parentNode) {
      jssStyles.parentNode.removeChild(jssStyles);
    }
  }
  ...
```
removed during client side execution.

How to accomplish this with your boilerplate app? I have guesses that it is just not necessary?

Thank you.

**Comment by nacmartin** [comment]
:DD Thanks, @sufius , very appreciated
